3MFConsortium/lib3mf

CMakeLists.txt
Source/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.cpp
Source/UnitTests/UnitTest_BeamLattice.cpp

If r1 and r2 are different, but r1 matches the default radius, it will only write r2, which is against spec.
Just added a condition where if r1 matches the default and r1 and r2 are different, write r1.

fixed beamlattice bug where only r2 writes

---

CMakeLists.txt
Release/VersionInfo/VersionResource.rc

Fixes part of
https://github.com/3MFConsortium/lib3mf/issues/8  
and correctly sets the "Product Version" for Windows to "Major.Minor.Patch" instead of "Major.Minor"

Fix binary name

---

CMakeLists.txt

Install target for the library + header files.
This still installs the google test files as before in case LIB3MF_TESTS is enabled.
Tested on Debian/Testing using packages [built on OBS](https://build.opensuse.org/package/show/home:t-paul:lib3mf/lib3mf) using [3MF import/export branch](https://github.com/openscad/openscad/pull/1802) of OpenSCAD.

Add install target for library and header files.

---

CMakeLists.txt
Include/Common/NMR_ErrorConst.h
Source/Common/NMR_Exception.cpp
Source/Common/NMR_UUID.cpp
Source/Common/Platform/NMR_ExportStream_GCC_Native.cpp
Source/Common/Platform/NMR_ImportStream_GCC_Native.cpp
Source/Common/Platform/NMR_Time.cpp
Source/Main/dllmain.cpp

This pull request is initial work to get lib3MF building on MinGW. Specifically this would enable use of lib3MF in OpenSCAD for Windows which is using the MXE build environment.
The changes from this pull request allow building of the library, but there's still issues open, so this is also a __request for help__ to track down the remaining issues.
Changes so far:
- Use lower case windows.h which should be compatible with all platforms
- Add missing GCC-Win32 file to CMakeLists.txt
- Don't use `wchar_t` in `open()` calls in the native stream handlers
Open issues:
- Still producing `liblib3MF` file name, even with the proposed fix in #34 
- Errors when generating 3MF file in `lib3mf_model_addmeshobject()` with `A UUID is not unique within a package. (000080ad)`
- It would help to be able to …

MinGW win32 build / MXE

---

Include/Model/Classes/NMR_ModelConstants.h
Source/Model/Reader/v100/NMR_ModelReaderNode100_Resources.cpp
Source/UnitTests/UnitTest_Thumbnails.cpp

Add warning when reading multiproperties

---

Include/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.h

To address https://github.com/3MFConsortium/lib3mf/issues/28 .
Apart from this, you should consider using lib3mf_model_setunit to change the length-unit inside a 3MF package.

Increase precision for floating point export

---

.gitmodules

Use public URL instead of SSH URL to avoid authentication errors when pulling from googltest.
See this for more details.  https://salferrarello.com/git-submodule-fatal-read-remote-repository/

Using public URL for googletest submodule

---

Source/Common/Platform/NMR_ExportStream_Memory.cpp
Source/Common/Platform/NMR_XmlReader_Native.cpp
Source/Libraries/libzip/zip_buffer.c
Source/Libraries/libzip/zip_close.c
Source/Libraries/libzip/zip_error_to_str.c
Source/Libraries/libzip/zip_open.c
Source/Libraries/libzip/zip_source_buffer.c
Source/Libraries/libzip/zip_source_deflate.c
Source/Model/COM/NMR_COMInterface_ModelWriter.cpp
UnitTests/Source/UnitTest_Attachments.cpp
UnitTests/Source/UnitTest_ReadWrite.cpp

* 32 bit builds need explicit cast when converting uint64 to size_t

Fix compiler warnings for VS Win32 build

---

LICENSE
SDK/GenerateSDK.sh

All former copyright holders (Microsoft Corporation, Autodesk Inc. and
netfabb GmbH) have contributed to lib3MF and continue to contribute to
lib3MF as members of the 3MF consortium.
The binary pakage lib3MF_sdk.zip now contains the LICENSE file.

Update copyright to 3MF-Consortium

---

CMakeLists.txt
Include/Common/NMR_ErrorConst.h
Source/Common/NMR_Exception.cpp
Source/Common/OPC/NMR_OpcPackageReader.cpp

Resolves #81
This allows lib3MF to read ZIP files with invalid headers.
- These mostly are files which 7Zip reports to have "Warning: Headers error": Lib3MF will issue a warning for these files, but attempt to read them.
- Files with full "Headers error" will still not be read by lib3MF.
See https://libzip.org/documentation/zip_open.html for reference of the flag in question.

Inconsistent ZIP files cause warnings

---

Source/Common/NMR_UUID.cpp

MinGW supports this API and adding libuuid to the Windows build is not easy as this is part of the util-linux package which has lots of Linux specific code.
This is tested via [MXE based build](https://circleci.com/gh/openscad/openscad/295#artifacts/containers/0) for OpenSCAD.
Trivial model (`cube(10);`) exported: [3dmodel.model.txt](https://github.com/3MFConsortium/lib3mf/files/2544563/3dmodel.model.txt)

Use Windows API for GUID generation on MinGW.

---

CMakeLists.txt

This way it's actually possible to use cmake-gui and build the library without building tests.

Update CMake to include building tests as option

---

CMakeLists.txt
Include/Common/Platform/NMR_ImportStream_Shared_Memory.h
Include/Common/Platform/NMR_ImportStream_Unique_Memory.h
Source/CMakeLists.txt
Source/Common/Platform/NMR_ImportStream_GCC_Native.cpp
Source/Common/Platform/NMR_ImportStream_GCC_Win32.cpp
Source/Common/Platform/NMR_ImportStream_Memory.cpp
Source/Common/Platform/NMR_ImportStream_Shared_Memory.cpp
Source/Common/Platform/NMR_ImportStream_Unique_Memory.cpp
Source/Common/Platform/NMR_ImportStream_ZIP.cpp
Source/Model/COM/NMR_COMInterface_Model.cpp
Source/Model/COM/NMR_COMInterface_ModelAttachment.cpp
Source/Model/COM/NMR_COMInterface_ModelReader.cpp
Source/Model/COM/NMR_COMInterface_ModelTexture2D.cpp
Source/Model/Classes/NMR_Model.cpp
Source/Model/Writer/NMR_ModelWriter_3MF_Native.cpp

With the current implementation of CImportStream_Memory it is not possible to reuse memory from the user supplied buffer, as it is implemented with a std::vector, which shall own its own memory. Apart from this detail, the CImportStream_Memory implementation does not require to use std::vector, as it is only accessed via indexing, which is also supported by a raw const nfByte *, which is the original type of the buffer parameter.
To support memory sharing I have subclassed CImportStream_Memory with CImportStream_Shared_Memory and CImportStream_Unique_Memory. The CImportStream_Memory is now an abstract class that manages the position of the memory being read. The CImportStream_Unique_Memory implemented the stream as the old CImportStream_Memory, with a std::vector. The …

Reuse memory when reading a Model from a Buffer

---

.travis.yml

It appears that
1. travis sometimes uses other than the default linux distribution (trusty, 14.04) specified here:
https://docs.travis-ci.com/user/reference/overview/#linux
2. the default setup of mingw on xenial (16.04) has trouble with std::mutex, which is why lib3mf builds fail on this machine.
Thus, this commit enforces trusty as distribution for the mandatory mingw-builds.

Fix mingw-build

---

.travis.yml
CI/Dockerfile
CI/script.sh
Include/Common/MeshImport/NMR_MeshImporter_STL.h
Include/Common/NMR_Architecture_Utils.h
Include/Common/Platform/NMR_PortableZIPWriterTypes.h
Source/Common/MeshExport/NMR_MeshExporter_STL.cpp
Source/Common/MeshImport/NMR_MeshImporter_STL.cpp
Source/Common/Platform/NMR_PortableZIPWriter.cpp
Tests/CPP_Bindings/Source/Reader.cpp

Fixes https://github.com/3MFConsortium/lib3mf/issues/160
This PR:
- fixes writing of .3mf-files on big endian-machines
- fixes reading and writing of .stl-files on big endian-machines
- modifies the travis-CI configuration to also build and test lib3mf on a big-endian linux machine. This build takes ~40 minutes though. It might need to be removed again to not hinder the development of lib3mf.
@knielsen: does this work for you/OpenSCAD?

Fix IO for big-endian machines

---

AutomaticComponentToolkit/lib3mf.xml
Include/API/lib3mf_writer.hpp
Include/Model/Writer/NMR_ModelWriter.h
Include/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.h
Include/Model/Writer/v100/NMR_ModelWriterNode100_Model.h
Source/API/lib3mf_writer.cpp
Source/Model/Writer/NMR_ModelWriter.cpp
Source/Model/Writer/NMR_ModelWriter_3MF.cpp
Source/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.cpp
Source/Model/Writer/v100/NMR_ModelWriterNode100_Model.cpp
Tests/CPP_Bindings/Source/Writer.cpp

Fixes https://github.com/3MFConsortium/lib3mf/issues/28.
Does not cover  #25 .
Writer-class gets new methods `GetDecimalPrecision` and `SetDecimalPrecision` which sets the number of decimal digits (after the decimal dot) that are serialized into a file.
Currently, only the 3mf-writer makes use of this. ASCII-STL-writer should respect this, too, at some point.
Verified that write performance is not degraded by this change.

Precision of float output can now be changed

---

Source/API/lib3mf_base.cpp

Resolves https://github.com/3MFConsortium/lib3mf/issues/170
Internal / generic exceptions (API error code 5) now correctly propagate to the client code.
Other exceptions will still only show their error code.

Fix GetLastError

---

CMakeLists.txt
lib3MF.pc.in

`lib3MF.so` is not explicitly linked against `libzip` or `zlib` even when `USE_INCLUDED_LIBZIP=OFF` or `USE_INCLUDED_ZLIB=OFF` are used. These dependencies are only specified in the "Libs" section of the [pkg-config file](https://github.com/3MFConsortium/lib3mf/blob/master/lib3MF.pc.in). People trying to link the library directly without relying on the pkg-config file will face errors like
```
/usr/bin/ld: lib3MF.so.1.8.1.0: undefined reference to `deflateInit2_'
```
This can be immediately observed when trying to compile lib3mf with
```
cmake -DUSE_INCLUDED_LIBZIP=OFF -DUSE_INCLUDED_ZLIB=OFF
-DLIB3MF_TESTS=ON
```
The solution is to link lib3mf against all the necessary libraries so that they can be pulled in automatically during linking. This allows to move them from "Libs" to …

develop_v1_legacy: link against libzip/zlib when USE_INCLUDED_{LIBZIP,ZLIB}=OFF is used

---

CMakeLists.txt
UnitTests/CMakeLists.txt

This is a backport of PR #186 for the legacy version.

 develop_v1_legacy: add configuration option to use system Google Test

---

Source/Common/OPC/NMR_OpcPackageReader.cpp

This change is based on https://github.com/nih-at/libzip/issues/44
This PR fixes subissue 1 of https://github.com/3MFConsortium/lib3mf/issues/180 .

Fix memory leak in libzip when reading files

---

Source/Common/MeshImport/NMR_MeshImporter_STL.cpp
Tests/CPP_Bindings/Source/Reader.cpp

I don't know why, but it seems you commented out some code which is necessary to correctly read STLs. It simply does not add any faces to the mesh during the read process.
The addition of this single line makes the STL reader work again.

Add triangles during STL read

---

CMakeLists.txt
lib3mf.pc.in

This makes the necessary changes to have the existing lib3MF.pc.in file built in CMake again (as removed here https://github.com/3MFConsortium/lib3mf/commit/a32e2179e47e17601fb87e898f5a010b71238d98#diff-af3b638bc2a3e6c650974192a53c7291L147-L148)
I've also changed the casing of `lib3MF` to `lib3mf` on the pc file as the package name is lower case and so is the .so file.
Fixes #224 
And here's a test script for building with pkgconfig
```bash
set -e
mkdir build
cd build
mkdir usr
cmake -DCMAKE_INSTALL_PREFIX=usr -DLIB3MF_TESTS=0 ..
make -j
make install
(
cat <<EOF
#include "Bindings/C/lib3mf.h"
int main(){}
EOF
) > test.cc
flags=$(PKG_CONFIG_PATH=./usr/lib/pkgconfig pkg-config --cflags --libs lib3mf)
g++ $flags test.cc
LD_LIBRARY_PATH=./usr/lib ./a.out && echo 'SUCCESS' || echo 'FAIL' …
```

Add pkgconfig file back to CMake

---

Include/Common/Platform/NMR_XmlWriter_Native.h

Fixes `error C2039: 'string': is not a member of 'std'`
when compiling with MSVC ++ from VS 2017/2019

Add missing #include <string>

---

.github/workflows/build.yml
Tests/codecoverage/run_codecoverage.sh

Apparently, one needs to create a baseline for lcov first to capture source files with content that is not used _at all_.
( https://wiki.documentfoundation.org/Development/Lcov#Run_initial.2Fbaseline_lcov )
Having said that, it does not change the result. Probably, there are now unused files

Account for files not captured by the test

---

AutomaticComponentToolkit/lib3mf.xml
Include/API/lib3mf_triangleset.hpp
Source/API/lib3mf_triangleset.cpp
Source/CMakeLists.txt
Source/Model/Reader/v100/NMR_ModelReaderNode100_TriangleSet.cpp

I made the following fixes:
1. Fixed the cmakelists to add missing .cpp files
2. Fixed a vs2015 issue with a constructor for CBase class that wasn't defined
3. Fixed triangleset reader to look for the correct element for triangle indices
I also added an API to query the TriangleSet indices

Trianglesets fixing cmake, cbase constructor, writer and adding api to get triangleset ids

---

Source/Common/OPC/NMR_OpcPackageContentTypesReader.cpp
Source/Common/OPC/NMR_OpcPackageWriter.cpp

Fixes https://github.com/3MFConsortium/lib3mf/issues/293

Issue-293: make override part names absolute

---

CMakeLists.txt

new PR for #290 , as this PR does not run through.
In Fedora, we strip them ourselves post-build and we keep the debuginfo. 
Original author: @hroncok

 Add a possibility not to strip binaries

---

.github/workflows/build.yml

Builds failed due to outdated runners and consistently failing code coverage test, so this PR sets the runners to the latest version.
This PR does not fix the code coverage test yet, only removes the dependency for the ci success on the code cov result.
Closes #323

Updating build.yml to fix failing ci builds

---

.github/workflows/build.yml
.gitmodules
CMakeLists.txt
Include/Common/NMR_StringUtils.h
Source/Common/NMR_StringUtils.cpp
Source/Model/Reader/v093/NMR_ModelReaderNode093_TextureVertex.cpp
Source/Model/Reader/v093/NMR_ModelReaderNode093_Vertex.cpp
Source/Model/Reader/v100/NMR_ModelReaderNode100_Vertex.cpp

Using fast_float as suggest by @bubnikv to resolve the issue addressed by #322.
PR is already based on #324 to make the ci pass.

Using fast_float to do local independent parsing

---

Include/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.h
Source/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.cpp

SetDecimalPrecision not working for values above 9 decimal places.
I notice in the [PR ](https://github.com/3MFConsortium/lib3mf/pull/169/files)that created this API that we cast a very large number to an int, when it should probably be a long long (m_nPutDoubleFactor). I stongly suspect this will fix the issue.

Issue 363: changing double factor from int to long long

---

Autogenerated/Bindings/Cpp/lib3mf_implicit.hpp
SDK/Examples/Cpp/CMakeLists.txt
SDK/Examples/Cpp/Source/FillMeshWithGyroid.cpp

Adding an additional example that generates a complete model.

3d jan/extend volumetric examples

---

Autogenerated/Bindings/CSharp/Lib3MF.cs

https://github.com/3MFConsortium/lib3mf/issues/284
When passing user-defined struct from CSharp bindings to C++, ref should be used to receive them as pointers in implementation side, if its not used it should be received as Value.
This is a direct patch, in the next release updating of ACT will resolve this issue.

ISSUE-284: fix CSharp crash when passing struct
